### ISSUE TITLE
make favicon less sus

### ISSUE THREAD

**Issue by InspectorConstructor** [InspectorConstructor/litsus#1]
make the awesome favicon look better

**Comment by belthesar** [comment]
plz use app standard terminology when describing issues kthx

**Comment by InspectorConstructor** [comment]
Sorry baws, will do for all future issues.

On Mon, Jan 25, 2016 at 12:48 AM, Cody Wilson <notifications@github.com>
wrote:

> plz use app standard terminology when describing issues kthx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/InspectorConstructor/litsus/issues/1#issuecomment-174410786>
> .
>



-- 
Nick
