### ISSUE TITLE
Android, Chrome: No sound

### ISSUE THREAD

**Issue by belthesar** [InspectorConstructor/litsus#10]
Tested on Samsung Galaxy Tab

**Comment by InspectorConstructor** [comment]
turns out mobile sound is tough. will try some special js-foo tomorrow

**Comment by belthesar** [comment]
Is the code for sound disabled on mobile? (Haven't tested) - If not, leave on.

**Comment by InspectorConstructor** [comment]
it just doesn't seem to work on mobile
